[build]
  command   = "npm run build"
  publish   = "out"

[build.environment]
  NODE_VERSION                  = "20"
  NEXT_PUBLIC_API_BASE_URL      = "https://vflco2pvo3.execute-api.us-east-2.amazonaws.com/prod"
  NEXT_PUBLIC_AWS_REGION        = "us-east-2"

[functions]
  directory = "netlify/functions"
